### ISSUE TITLE
Tremor chart crashes due to files being listed via find multiple times.

### ISSUE THREAD

**Issue by ekarlso** [tremor-rs/tremor-k8s-helm#8]
```find /etc/tremor/config/ -name '*.troy'
/etc/tremor/config/..2022_05_15_20_20_08.910613383/config.troy
/etc/tremor/config/config.troy``` 

This will cause Tremor to crash when starting, maybe it should filter out the files that are under the k8s based subfolder?

**Comment by darach** [comment]
Which process is generating the `/..2022_05_15_20_20_08.910613383/` directory so we can try and replicate?

**Comment by njegosrailic** [comment]
Hi,

thanks. It would be great if you could provide more details about what are you trying to accomplish.

Do you just need one more file inside the config directory? The container will crash if there is no default config file. It means if we are going to change this file name then we may have to change the entry point and some other parameters.

**Comment by ekarlso** [comment]
Example values below, insert a random simple `.troy` file and it should replicate the issue, then you need to install the helmchart into a cluster like `helm upgrade -i -f values.yaml <chart> tremor` and it should start creashing due to duplicate file being loaded.

```yaml
files:
  config.troy: |
    replaceme
```

**Comment by njegosrailic** [comment]
I have tested it with the following values and it works:

```
files:
  config.yaml: |-
    onramp:
      - id: metronome
        type: metronome
        config:
          interval: 10000
    binding:
      - id: default
        links:
          '/onramp/metronome/{instance}/out': [ '/pipeline/main/{instance}/in' ]
          '/pipeline/main/{instance}/out': [ '/offramp/system::stdout/system/in' ]
          '/pipeline/system::metrics/system/out': [ '/offramp/system::stdout/system/in' ]
    mapping:
      /binding/default/01:
        instance: '01'
  config.troy: |
    replaceme
  main.trickle: select event from in into out
```

I'm not sure what's the `config.troy` but likely the container fails because it can't find the default config.
